"""initial schema

Revision ID: c0d309d2bd74
Revises: 
Create Date: 2026-08-09 12:30:01.798563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d309d2bd74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('defects_processed', sa.Integer(), nullable=False),
    sa.Column('budget_available', sa.Float(), nullable=True),
    sa.Column('num_crews', sa.Integer(), nullable=True),
    sa.Column('priority_breakdown', sa.JSON(), nullable=True),
    sa.Column('total_estimated_cost', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=True),
    sa.Column('road_age_years', sa.Float(), nullable=True),
    sa.Column('material_type', sa.Integer(), nullable=True),
    sa.Column('daily_vehicles', sa.Integer(), nullable=True),
    sa.Column('last_repair_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('road_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('class_code', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('severity_level', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('road_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('current_severity', sa.Float(), nullable=False),
    sa.Column('forecast_days', sa.Integer(), nullable=False),
    sa.Column('predicted_severity', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('remaining_life_years', sa.Float(), nullable=True),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('road_id', sa.String(), nullable=True),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('defect_class', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('recommended_repair', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('time_required_days', sa.Float(), nullable=True),
    sa.Column('assigned_crew', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repairs')
    op.drop_table('simulation_results')
    op.drop_table('detections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roads')
    op.drop_table('request_logs')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
